# Generated by Django 5.0.7 on 2024-07-15 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('passkey', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('equipment', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('recipe', models.JSONField()),
            ],
        ),
    ]
